version: '3.2'
services:
  tileserver-gl:
    build: .
    image: mapas-barragens-tileserver:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CACHE_SIZE=500m
    volumes:
      - /mnt/maps-data:/data/mbtiles
    ports:
      - "8090:8080"
